<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>CalcModuleKCRV</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ValidateService\CSV_Checkers\**" />
    <Compile Remove="ValidateService\JSON_Checkers\**" />
    <Compile Remove="ValidateService\XLSX_Checkers\**" />
    <EmbeddedResource Remove="ValidateService\CSV_Checkers\**" />
    <EmbeddedResource Remove="ValidateService\JSON_Checkers\**" />
    <EmbeddedResource Remove="ValidateService\XLSX_Checkers\**" />
    <None Remove="ValidateService\CSV_Checkers\**" />
    <None Remove="ValidateService\JSON_Checkers\**" />
    <None Remove="ValidateService\XLSX_Checkers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.2.1" />
    <PackageReference Include="itext7" Version="7.2.5" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KCRV_Statistics.Core\KCRV_Statistics.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ValidateService\SimpleFileCheckers\" />
  </ItemGroup>

</Project>
